application : ragilfrontend
runtime : python27
version : 1
api_version : 1
threadsafe : true

libraries:
- name: webapp2
  version: "latest"

handlers:

- url : /(hc|phone)/(.*?\.)(js|css|eot|woff2|woff|ttf|jpg|png|svg|gif)
  static_files : static/\1/\2\3
  upload : static/.*
  login : admin
  secure : always

- url : /(hc|phone)
  script: redirect.app

- url : /(hc|phone)/.*
  static_files : static/\1/index.html
  upload : static/.*
  login : admin
  secure : always
