application : ragilfrontend
runtime : python27
version : 1
api_version : 1
threadsafe : true

libraries:
- name: webapp2
  version: "latest"

handlers:

- url : /hc/(.*?\.)(js|css|eot|woff2|woff|ttf|jpg|png|svg|gif)
  static_files : static/hc/\1\2
  upload : static/hc/.*
  login : admin
  secure : always

- url : /hc
  script: redirect.app

- url : /hc/.*
  static_files : static/hc/index.html
  upload : static/hc/index.html
  login : admin
  secure : always
